### ISSUE TITLE
Cannot read property 'include' of undefined

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet.Editable#42]
I'm getting this error right after including the library:

![image](https://cloud.githubusercontent.com/assets/2399810/11088542/582b257a-8863-11e5-9fca-fb61d3528ef7.png)

any ideas?

**Comment by codeofsumit** [comment]
maybe I'm using the wrong version of this plugin? I used bower like so as I was under the impression that the gh-pages branch is being pulled and ready for leaflet 1.0 beta.

`"leaflet.editable": "~0.6.2",`.

Is this wrong?

**Comment by cmulders** [comment]
Possibly because the Leaflet library should be loaded before Editable, I do not know if bower is aware of this dependency? (bower.json does not specify the leaflet dependency)
If this is not the case, please paste here the specific line in your environment (Line 1054 in this case). 

I am using L.Editable with no problems so far (with Leaflet 1.0 beta2)! But I am not using bower for dependency management.

**Comment by cmulders** [comment]
Ah I see, L.Editable 0.6.2 is still using the removed L.Multi* vectors. If you use Leaflet 1.0.0 beta, you should use the 0.7.0-beta release of L.Editable!
```is
Line 1054: L.MultiPolygon.include(MultiEditableMixin);
Line 1055: L.MultiPolyline.include(MultiEditableMixin);
```

**Comment by yohanboniface** [comment]
> L.Editable 0.6.2 is still using the removed L.Multi* vectors. If you use Leaflet 1.0.0 beta, you should use the 0.7.0-beta release of L.Editable!

Correct :)
