### ISSUE TITLE
Cancel editing is complicated

### ISSUE THREAD

**Issue by Kulikovpavel** [Leaflet/Leaflet.Editable#55]
Hello. I cant find easy way to cancel editing, so must write this:
```
map.on('editable:drawing:cancel', function (e) {
	map.removeLayer(e.layer);
});
	
var onKeyDown = function (e) {
	if (e.keyCode == 27) {  // esc button
		if (!this.editTools._drawingEditor) {return;};
	   	map.editTools._drawingEditor.disable();
	}
};
L.DomEvent.addListener(document, 'keydown', onKeyDown, map);
```

Is there other way? Maybe need to put something in plugin?

**Comment by yohanboniface** [comment]
Leaflet.Editable is a hookable close to non opinionated library, so it try not to make as little assumptions as possible. For what I understand of your code, you want two things:
- remove a layer on cancel: this may be added as default behaviour *when the edited layer is invalid*, but not in all cases imho (see #51)
- cancel editing on escape pressed: listening for keyboard events is very tied to the UI of the app, and it's not really possible to listen for those event in a non obtrusive way, so I think it's better for Leaflet.Editable not to go this way

So in my point of view, and because we can't do that in a generic non obtrusive way, it's OK to have to write those 10 lines of JS to handle this the way you exactly want.

That said, some hook may be missing. Feel free to reopen if you think of some that should be added.
