### ISSUE TITLE
vertexCanBeDeleted question

### ISSUE THREAD

**Issue by dhollema** [Leaflet/Leaflet.Editable#63]
I'm debugging an issue we're having in our application and I have a question.  Is the correct equality comparison being used in PolygonEditor to compare vertex latlngs to the underlying feature's latlngs?  I'm just making sure this isn't intended to be a "by value" comparison instead.

```
vertexCanBeDeleted: function(vertex) {
    if (vertex.latlngs === this.getLatLngs()) return L.Editable.PathEditor.prototype.vertexCanBeDeleted.call(this, vertex);
    else return true; // Holes can be totally deleted without removing the layer itself
}
```

**Comment by yohanboniface** [comment]
Which version are you using?

This has been changed in the master: https://github.com/Leaflet/Leaflet.Editable/blob/gh-pages/src/Leaflet.Editable.js#L1164
Master is not yet released though because I'm waiting for a Leaflet new release to do so, which should come quickly. If you are using the Leaflet.Editable 0.7.0-beta1, you may want to just use the master until next release. If you are on the stable Leaflet/Leaflet.Editable branch, humm, that will be a bit more complex, and you should actually update ;)

**Comment by dhollema** [comment]
Yes, this fixed the issue.  Thx.
